### ISSUE TITLE
clothing parsing / keypoints model

### ISSUE THREAD

**Issue by chenxiao521** [RuiLiFeng/Deep-Generative-Projection#3]
Your work is amazing，Can you release the clothing parsing / keypoints model as soon as possible。

**Comment by RuiLiFeng** [comment]
Thanks for your attention!

The parsing and keypoints models belong to the Alibaba Group. They are initially provided by the search recommendation team of Taobao.  We are working on making it open source. This means red tapes of the legal and business processes. But I think we can finish it before the Autumn.

**Comment by RuiLiFeng** [comment]
Thanks for your attention!

The parsing and keypoints models belong to the Alibaba Group. They are
initially provided by the search recommendation team of Taobao.  We are
working on making it open source. This means red tapes of the legal and
business processes. But I think we can finish it before the Autumn.

chenxiao521 ***@***.***> 于2022年5月6日周五 09:52写道：
