### ISSUE TITLE
data release

### ISSUE THREAD

**Issue by nourgana** [RuiLiFeng/Deep-Generative-Projection#6]
Hi, 
Is the ESF dataset gonna be available  anytime soon?

**Comment by RuiLiFeng** [comment]
I am now uploading it to OneDrive, please wait.

**Comment by RuiLiFeng** [comment]
The ESF dataset has now been uploaded. Check it in ReadMe plz.

**Comment by RayTang88** [comment]
Hello,
   we have noticed that the download link for ESF is not very stable and is almost impossible to download successfully. Is there a new link available? We look forward to your reply. Thank you very much!

**Comment by RuiLiFeng** [comment]
Hi RayTang88,

Thank you for getting in contact. I will see how to solve this.

Best,

Ruili

RayTang88 ***@***.***> 于2024年9月25日周三 15:59写道：
