### ISSUE TITLE
Problem in inference 

### ISSUE THREAD

**Issue by AliYqb** [RuiLiFeng/Deep-Generative-Projection#7]
Hello, Thanks for great job.

Why do I get different results from readme results after executing code from some of the examples you gave?
Can you help me get better outputs?

![outputs_pattern_search2](https://user-images.githubusercontent.com/79134287/171388818-cfebdd0e-597d-495c-a847-8149bc8467a1.png)
![outputs_pattern_search3](https://user-images.githubusercontent.com/79134287/171388845-080a1903-83aa-4dd8-a6be-af87067e1c49.png)

**Comment by miibotree** [comment]
> Hello, Thanks for great job.
> 
> Why do I get different results from readme results after executing code from some of the examples you gave? Can you help me get better outputs?
> 
> ![outputs_pattern_search2](https://user-images.githubusercontent.com/79134287/171388818-cfebdd0e-597d-495c-a847-8149bc8467a1.png) ![outputs_pattern_search3](https://user-images.githubusercontent.com/79134287/171388845-080a1903-83aa-4dd8-a6be-af87067e1c49.png)

Please try to reduce the **projection_step** parameter to 50 steps. Setting the projection step too much will result in margin closer to the coarse alignment input. If that works, we will update the default step parameters.

**Comment by AliYqb** [comment]
Thank you for your answer
I got better results, but in the second result there are still weaknesses
For example, in the middle of the dress or in the collar buttons

![outputs_pattern_search2new](https://user-images.githubusercontent.com/79134287/172124547-294fd8c8-85b3-49d3-84cc-d80aaaa4ec6f.png)

![outputs_pattern_search3new](https://user-images.githubusercontent.com/79134287/172124607-98c6818a-c84e-4e71-9066-4cd52b2dd15e.png)

**Comment by miibotree** [comment]
> Thank you for your answer I got better results, but in the second result there are still weaknesses For example, in the middle of the dress or in the collar buttons
> 
> ![outputs_pattern_search2new](https://user-images.githubusercontent.com/79134287/172124547-294fd8c8-85b3-49d3-84cc-d80aaaa4ec6f.png)
> 
> ![outputs_pattern_search3new](https://user-images.githubusercontent.com/79134287/172124607-98c6818a-c84e-4e71-9066-4cd52b2dd15e.png)

We've updated the default step parameters. Please try again.
